# -*- encoding: utf-8 -*-

=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "gb_retailapi_client/version"

Gem::Specification.new do |s|
  s.name        = "gb_retailapi_client"
  s.version     = GbRetailapiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["GroupBy Inc."]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "GroupBy Retail Ruby Gem"
  s.description = "GroupBy Retail API"
  s.license     = "UNLICENSED"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
