=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for GbRetailapiClient::AutocompleteApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AutocompleteApi' do
  before do
    # run before each test
    @api_instance = GbRetailapiClient::AutocompleteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AutocompleteApi' do
    it 'should create an instance of AutocompleteApi' do
      expect(@api_instance).to be_instance_of(GbRetailapiClient::AutocompleteApi)
    end
  end

  # unit tests for autocompletesearch
  # A simple request used to get completes the specified prefix with keyword suggestions.
  # @param x_groupby_customer_id Header on incoming HTTP requests that is populated by the API gateway and indicates the customer ID.
  # @param identity 
  # @param merchandiser 
  # @param [Hash] opts the optional parameters
  # @option opts [Request] :request Object which is represent autocomplete request and encapsulate all passed parameters. 
  # @return [SearchResults]
  describe 'autocompletesearch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
