=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for GbRetailapiClient::ProductApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProductApi' do
  before do
    # run before each test
    @api_instance = GbRetailapiClient::ProductApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductApi' do
    it 'should create an instance of ProductApi' do
      expect(@api_instance).to be_instance_of(GbRetailapiClient::ProductApi)
    end
  end

  # unit tests for get_by_product_ids
  # Provided product search functionality
  # Perform a product search against the GroupBy Retail Search API.
  # @param collection Collection name
  # @param product_id Product ID which need to be search
  # @param x_groupby_customer_id Required. This parameter will extract from header X-Groupby-Customer-Id. May contain tenant name. Used to define a                           client by its name.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :variant_ids Not required. If the product has variant list and the request specifies the variantIds, requested variants will be the                           first in the response.
  # @return [ProductDto]
  describe 'get_by_product_ids test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
