=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for GbRetailapiClient::RecommendationsAPIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecommendationsAPIApi' do
  before do
    # run before each test
    @api_instance = GbRetailapiClient::RecommendationsAPIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecommendationsAPIApi' do
    it 'should create an instance of RecommendationsAPIApi' do
      expect(@api_instance).to be_instance_of(GbRetailapiClient::RecommendationsAPIApi)
    end
  end

  # unit tests for predict
  # Provide Recommendations AI functionality.
  # Perform a recommendation request against the GroupBy Retail Recommendations API.
  # @param x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name.
  # @param recommendations_request Request that should be populated to configure a recommendations API call made by the client.
  # @param [Hash] opts the optional parameters
  # @return [PredictResults]
  describe 'predict test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for predict_v2
  # Provide Recommendations AI functionality.
  # Perform a recommendation request against the GroupBy Retail Recommendations API.
  # @param x_groupby_customer_id Custom HTTP header which may contain tenant name. Used to define a client by its name.
  # @param recommendations_request Request that should be populated to configure a recommendations API call made by the client.
  # @param [Hash] opts the optional parameters
  # @return [PredictResults]
  describe 'predict_v2 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
