=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module GbRetailapiClient
  class BiasDtoStrengthDto
    ABSOLUTE_INCREASE = "ABSOLUTE_INCREASE".freeze
    STRONG_INCREASE = "STRONG_INCREASE".freeze
    MEDIUM_INCREASE = "MEDIUM_INCREASE".freeze
    WEAK_INCREASE = "WEAK_INCREASE".freeze
    LEAVE_UNCHANGED = "LEAVE_UNCHANGED".freeze
    WEAK_DECREASE = "WEAK_DECREASE".freeze
    MEDIUM_DECREASE = "MEDIUM_DECREASE".freeze
    STRONG_DECREASE = "STRONG_DECREASE".freeze
    ABSOLUTE_DECREASE = "ABSOLUTE_DECREASE".freeze

    def self.all_vars
      @all_vars ||= [ABSOLUTE_INCREASE, STRONG_INCREASE, MEDIUM_INCREASE, WEAK_INCREASE, LEAVE_UNCHANGED, WEAK_DECREASE, MEDIUM_DECREASE, STRONG_DECREASE, ABSOLUTE_DECREASE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if BiasDtoStrengthDto.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #BiasDtoStrengthDto"
    end
  end
end
