=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module GbRetailapiClient
  class QueryPatternTriggerType
    CONTAINS = "CONTAINS".freeze
    ENDS_WITH = "ENDS_WITH".freeze
    REGEX = "REGEX".freeze
    STARTS_WITH = "STARTS_WITH".freeze
    MATCHES = "MATCHES".freeze

    def self.all_vars
      @all_vars ||= [CONTAINS, ENDS_WITH, REGEX, STARTS_WITH, MATCHES].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if QueryPatternTriggerType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #QueryPatternTriggerType"
    end
  end
end
