=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module GbRetailapiClient
  # Object which is represent autocomplete request and encapsulate all passed parameters. 
  class Request
    # Area i.e. 'Production' Will not be used immediately. This will be useful when we eventually need to support a US area vs a Canada area. But this would require using the custom dataset instead of user-generated.
    attr_accessor :area

    # Name of the collection used to determine the retail backend to use. Usually it is name which is associated with retail project in command center (project configuration).
    attr_accessor :collection

    # Completion max suggestions. The maximum allowed max suggestions is 20.
    attr_accessor :search_items

    # String. Required. The query used to generate suggestions. The maximum number of allowed characters is 255.
    attr_accessor :query

    # Enable attribute suggestions, by setting the field enableAttributeSuggestion=true in the API request. Then in response, there will be an additional field attributeResults to show direct match results on brands/categories  Note that attribute results directly come from the products we import and Google does not apply any cleaning on them. 
    attr_accessor :enable_attribute_suggestion

    # Optional param which is define if extended suggestions will be returned in autocomplete response or not. Possibly values: true, false, not specified (If not specified default collection setting will be used). 
    attr_accessor :extended_suggestions

    #     List with extended attributes which are would be returned in autocomplete response.     Requires extendedSuggestions to be enabled using search param or on collection layer. 
    attr_accessor :extended_attributes

    # String. Not required field. A unique identifier for tracking visitors. For example, this could be implemented with an HTTP cookie, which should be able to uniquely identify a visitor on a single device. This unique identifier should not change if the visitor logs in or out of the website. The field must be a UTF-8 encoded string with a length limit of 128 characters. Otherwise, an INVALID_ARGUMENT error is returned. 
    attr_accessor :visitor_id

    # Name of site filter. If not specified, the specified area's default site will be applied if configured in Command Center. To not use default specify empty value i.e.\"\".  If the site doesn't exist then the search will execute without the site filter.
    attr_accessor :site

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'area' => :'area',
        :'collection' => :'collection',
        :'search_items' => :'searchItems',
        :'query' => :'query',
        :'enable_attribute_suggestion' => :'enableAttributeSuggestion',
        :'extended_suggestions' => :'extendedSuggestions',
        :'extended_attributes' => :'extendedAttributes',
        :'visitor_id' => :'visitorId',
        :'site' => :'site'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'area' => :'String',
        :'collection' => :'String',
        :'search_items' => :'Integer',
        :'query' => :'String',
        :'enable_attribute_suggestion' => :'Boolean',
        :'extended_suggestions' => :'Boolean',
        :'extended_attributes' => :'Array<String>',
        :'visitor_id' => :'String',
        :'site' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'extended_suggestions',
        :'extended_attributes',
        :'visitor_id',
        :'site'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GbRetailapiClient::Request` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GbRetailapiClient::Request`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'area')
        self.area = attributes[:'area']
      else
        self.area = nil
      end

      if attributes.key?(:'collection')
        self.collection = attributes[:'collection']
      else
        self.collection = nil
      end

      if attributes.key?(:'search_items')
        self.search_items = attributes[:'search_items']
      else
        self.search_items = nil
      end

      if attributes.key?(:'query')
        self.query = attributes[:'query']
      else
        self.query = nil
      end

      if attributes.key?(:'enable_attribute_suggestion')
        self.enable_attribute_suggestion = attributes[:'enable_attribute_suggestion']
      end

      if attributes.key?(:'extended_suggestions')
        self.extended_suggestions = attributes[:'extended_suggestions']
      end

      if attributes.key?(:'extended_attributes')
        if (value = attributes[:'extended_attributes']).is_a?(Array)
          self.extended_attributes = value
        end
      end

      if attributes.key?(:'visitor_id')
        self.visitor_id = attributes[:'visitor_id']
      end

      if attributes.key?(:'site')
        self.site = attributes[:'site']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @area.nil?
        invalid_properties.push('invalid value for "area", area cannot be nil.')
      end

      if @area.to_s.length > 80
        invalid_properties.push('invalid value for "area", the character length must be smaller than or equal to 80.')
      end

      if @collection.nil?
        invalid_properties.push('invalid value for "collection", collection cannot be nil.')
      end

      if @collection.to_s.length > 80
        invalid_properties.push('invalid value for "collection", the character length must be smaller than or equal to 80.')
      end

      if @collection.to_s.length < 1
        invalid_properties.push('invalid value for "collection", the character length must be great than or equal to 1.')
      end

      if @search_items.nil?
        invalid_properties.push('invalid value for "search_items", search_items cannot be nil.')
      end

      if @search_items > 20
        invalid_properties.push('invalid value for "search_items", must be smaller than or equal to 20.')
      end

      if @search_items < 1
        invalid_properties.push('invalid value for "search_items", must be greater than or equal to 1.')
      end

      if @query.nil?
        invalid_properties.push('invalid value for "query", query cannot be nil.')
      end

      if @query.to_s.length > 255
        invalid_properties.push('invalid value for "query", the character length must be smaller than or equal to 255.')
      end

      if @query.to_s.length < 1
        invalid_properties.push('invalid value for "query", the character length must be great than or equal to 1.')
      end

      if !@extended_attributes.nil? && @extended_attributes.length < 1
        invalid_properties.push('invalid value for "extended_attributes", number of items must be greater than or equal to 1.')
      end

      if !@visitor_id.nil? && @visitor_id.to_s.length > 128
        invalid_properties.push('invalid value for "visitor_id", the character length must be smaller than or equal to 128.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @area.nil?
      return false if @area.to_s.length > 80
      return false if @collection.nil?
      return false if @collection.to_s.length > 80
      return false if @collection.to_s.length < 1
      return false if @search_items.nil?
      return false if @search_items > 20
      return false if @search_items < 1
      return false if @query.nil?
      return false if @query.to_s.length > 255
      return false if @query.to_s.length < 1
      return false if !@extended_attributes.nil? && @extended_attributes.length < 1
      return false if !@visitor_id.nil? && @visitor_id.to_s.length > 128
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] area Value to be assigned
    def area=(area)
      if area.nil?
        fail ArgumentError, 'area cannot be nil'
      end

      if area.to_s.length > 80
        fail ArgumentError, 'invalid value for "area", the character length must be smaller than or equal to 80.'
      end

      @area = area
    end

    # Custom attribute writer method with validation
    # @param [Object] collection Value to be assigned
    def collection=(collection)
      if collection.nil?
        fail ArgumentError, 'collection cannot be nil'
      end

      if collection.to_s.length > 80
        fail ArgumentError, 'invalid value for "collection", the character length must be smaller than or equal to 80.'
      end

      if collection.to_s.length < 1
        fail ArgumentError, 'invalid value for "collection", the character length must be great than or equal to 1.'
      end

      @collection = collection
    end

    # Custom attribute writer method with validation
    # @param [Object] search_items Value to be assigned
    def search_items=(search_items)
      if search_items.nil?
        fail ArgumentError, 'search_items cannot be nil'
      end

      if search_items > 20
        fail ArgumentError, 'invalid value for "search_items", must be smaller than or equal to 20.'
      end

      if search_items < 1
        fail ArgumentError, 'invalid value for "search_items", must be greater than or equal to 1.'
      end

      @search_items = search_items
    end

    # Custom attribute writer method with validation
    # @param [Object] query Value to be assigned
    def query=(query)
      if query.nil?
        fail ArgumentError, 'query cannot be nil'
      end

      if query.to_s.length > 255
        fail ArgumentError, 'invalid value for "query", the character length must be smaller than or equal to 255.'
      end

      if query.to_s.length < 1
        fail ArgumentError, 'invalid value for "query", the character length must be great than or equal to 1.'
      end

      @query = query
    end

    # Custom attribute writer method with validation
    # @param [Object] extended_attributes Value to be assigned
    def extended_attributes=(extended_attributes)
      if !extended_attributes.nil? && extended_attributes.length < 1
        fail ArgumentError, 'invalid value for "extended_attributes", number of items must be greater than or equal to 1.'
      end

      @extended_attributes = extended_attributes
    end

    # Custom attribute writer method with validation
    # @param [Object] visitor_id Value to be assigned
    def visitor_id=(visitor_id)
      if !visitor_id.nil? && visitor_id.to_s.length > 128
        fail ArgumentError, 'invalid value for "visitor_id", the character length must be smaller than or equal to 128.'
      end

      @visitor_id = visitor_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          area == o.area &&
          collection == o.collection &&
          search_items == o.search_items &&
          query == o.query &&
          enable_attribute_suggestion == o.enable_attribute_suggestion &&
          extended_suggestions == o.extended_suggestions &&
          extended_attributes == o.extended_attributes &&
          visitor_id == o.visitor_id &&
          site == o.site
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [area, collection, search_items, query, enable_attribute_suggestion, extended_suggestions, extended_attributes, visitor_id, site].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = GbRetailapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
