=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GbRetailapiClient::Order
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GbRetailapiClient::Order do
  let(:instance) { GbRetailapiClient::Order.new }

  describe 'test an instance of Order' do
    it 'should create an instance of Order' do
      expect(instance).to be_instance_of(GbRetailapiClient::Order)
    end
  end
end
