=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GbRetailapiClient::PriceInfoPriceEffectiveTime
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GbRetailapiClient::PriceInfoPriceEffectiveTime do
  let(:instance) { GbRetailapiClient::PriceInfoPriceEffectiveTime.new }

  describe 'test an instance of PriceInfoPriceEffectiveTime' do
    it 'should create an instance of PriceInfoPriceEffectiveTime' do
      expect(instance).to be_instance_of(GbRetailapiClient::PriceInfoPriceEffectiveTime)
    end
  end
  describe 'test attribute "seconds"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "nanos"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
