=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GbRetailapiClient::RecommendationsErrorResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GbRetailapiClient::RecommendationsErrorResponse do
  let(:instance) { GbRetailapiClient::RecommendationsErrorResponse.new }

  describe 'test an instance of RecommendationsErrorResponse' do
    it 'should create an instance of RecommendationsErrorResponse' do
      expect(instance).to be_instance_of(GbRetailapiClient::RecommendationsErrorResponse)
    end
  end
  describe 'test attribute "tracking_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "method"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "path"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
