=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GbRetailapiClient::SearchRequestDtoOverwrites
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GbRetailapiClient::SearchRequestDtoOverwrites do
  let(:instance) { GbRetailapiClient::SearchRequestDtoOverwrites.new }

  describe 'test an instance of SearchRequestDtoOverwrites' do
    it 'should create an instance of SearchRequestDtoOverwrites' do
      expect(instance).to be_instance_of(GbRetailapiClient::SearchRequestDtoOverwrites)
    end
  end
  describe 'test attribute "rules"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
