=begin
#GroupBy Retail

#GroupBy Retail API

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

# Common files
require 'gb_retailapi_client/api_client'
require 'gb_retailapi_client/api_error'
require 'gb_retailapi_client/version'
require 'gb_retailapi_client/configuration'

# Models
require 'gb_retailapi_client/models/additional_info'
require 'gb_retailapi_client/models/attribute_suggestion'
require 'gb_retailapi_client/models/audience'
require 'gb_retailapi_client/models/bias_dto'
require 'gb_retailapi_client/models/bias_dto_strength_dto'
require 'gb_retailapi_client/models/biasing_profile_dto'
require 'gb_retailapi_client/models/boosted_product_bucket'
require 'gb_retailapi_client/models/color_info'
require 'gb_retailapi_client/models/custom_parameter_dto'
require 'gb_retailapi_client/models/custom_parameter_trigger'
require 'gb_retailapi_client/models/debug_dto'
require 'gb_retailapi_client/models/error_dto'
require 'gb_retailapi_client/models/error_response'
require 'gb_retailapi_client/models/experiment'
require 'gb_retailapi_client/models/experiment_variant'
require 'gb_retailapi_client/models/facet'
require 'gb_retailapi_client/models/facet_search_request_dto'
require 'gb_retailapi_client/models/facet_search_response_dto'
require 'gb_retailapi_client/models/field_mask'
require 'gb_retailapi_client/models/filter'
require 'gb_retailapi_client/models/filter_parameter'
require 'gb_retailapi_client/models/fulfillment_info'
require 'gb_retailapi_client/models/identity'
require 'gb_retailapi_client/models/image'
require 'gb_retailapi_client/models/interval'
require 'gb_retailapi_client/models/merchandiser'
require 'gb_retailapi_client/models/message_type'
require 'gb_retailapi_client/models/metadata'
require 'gb_retailapi_client/models/navigation_dto'
require 'gb_retailapi_client/models/navigation_type'
require 'gb_retailapi_client/models/navigation_type_dto'
require 'gb_retailapi_client/models/order'
require 'gb_retailapi_client/models/overwrites'
require 'gb_retailapi_client/models/page_info_dto'
require 'gb_retailapi_client/models/pinned_refinement'
require 'gb_retailapi_client/models/predict_results'
require 'gb_retailapi_client/models/price_info'
require 'gb_retailapi_client/models/price_info_price_effective_time'
require 'gb_retailapi_client/models/price_info_price_expire_time'
require 'gb_retailapi_client/models/price_info_price_range'
require 'gb_retailapi_client/models/price_info_price_range_original_price'
require 'gb_retailapi_client/models/price_info_price_range_price'
require 'gb_retailapi_client/models/product_custom_attribute'
require 'gb_retailapi_client/models/product_dto'
require 'gb_retailapi_client/models/product_dto_audience'
require 'gb_retailapi_client/models/product_dto_available_time'
require 'gb_retailapi_client/models/product_dto_color_info'
require 'gb_retailapi_client/models/product_dto_price_info'
require 'gb_retailapi_client/models/product_dto_publish_time'
require 'gb_retailapi_client/models/product_dto_rating'
require 'gb_retailapi_client/models/product_dto_retrievable_fields'
require 'gb_retailapi_client/models/promotion'
require 'gb_retailapi_client/models/query_pattern_trigger'
require 'gb_retailapi_client/models/query_pattern_trigger_type'
require 'gb_retailapi_client/models/range'
require 'gb_retailapi_client/models/range_filter'
require 'gb_retailapi_client/models/rating'
require 'gb_retailapi_client/models/recommendations_error_response'
require 'gb_retailapi_client/models/recommendations_request'
require 'gb_retailapi_client/models/record_dto'
require 'gb_retailapi_client/models/refinement'
require 'gb_retailapi_client/models/refinement_dto'
require 'gb_retailapi_client/models/request'
require 'gb_retailapi_client/models/role'
require 'gb_retailapi_client/models/rule_configuration'
require 'gb_retailapi_client/models/rule_template'
require 'gb_retailapi_client/models/rule_template_section'
require 'gb_retailapi_client/models/rule_type'
require 'gb_retailapi_client/models/rule_variant'
require 'gb_retailapi_client/models/search_filter'
require 'gb_retailapi_client/models/search_metadata_dto'
require 'gb_retailapi_client/models/search_request_dto'
require 'gb_retailapi_client/models/search_request_dto_overwrites'
require 'gb_retailapi_client/models/search_response_dto'
require 'gb_retailapi_client/models/search_results'
require 'gb_retailapi_client/models/search_results_stats'
require 'gb_retailapi_client/models/search_terms'
require 'gb_retailapi_client/models/selected_refinement_dto'
require 'gb_retailapi_client/models/selected_refinement_trigger'
require 'gb_retailapi_client/models/selected_refinement_trigger_type'
require 'gb_retailapi_client/models/sort'
require 'gb_retailapi_client/models/sort_dto'
require 'gb_retailapi_client/models/sort_dto_order_dto'
require 'gb_retailapi_client/models/spell_correction_mode'
require 'gb_retailapi_client/models/stats'
require 'gb_retailapi_client/models/template_dto'
require 'gb_retailapi_client/models/template_dto_trigger_set'
require 'gb_retailapi_client/models/timestamp'
require 'gb_retailapi_client/models/trigger_set'
require 'gb_retailapi_client/models/value_filter'
require 'gb_retailapi_client/models/value_filter_value_filter_type'
require 'gb_retailapi_client/models/zone_dto'
require 'gb_retailapi_client/models/zone_dto_type'
require 'gb_retailapi_client/models/zone_type'

# APIs
require 'gb_retailapi_client/api/autocomplete_api'
require 'gb_retailapi_client/api/product_api'
require 'gb_retailapi_client/api/recommendations_api_api'
require 'gb_retailapi_client/api/search_api'

module GbRetailapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   GbRetailapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
